version: "2"

services:
  # ================= virual vm 01
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - 9200:9200
      - 9600:9300
    environment:
      - discovery.type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # ================= virual vm 02
  cerebro:
    image: lmenezes/cerebro
    ports:
      - 9090:9000
    links:
      - es01
    depends_on:
      - es01
